<PACKAGE "HOOKS">

<ENTRY ADD-FINISHER>

<SETG PRE-COMPILE-HOOKS '()>

<DEFINE ADD-FINISHER (HANDLER)
    #DECL ((HANDLER) APPLICABLE)
    <INSTALL-PRE-COMPILE-HOOK>
    <SETG PRE-COMPILE-HOOKS (.HANDLER !,PRE-COMPILE-HOOKS)>>

<DEFINE PRE-COMPILE-HOOK-F ()
    <MAPF <> ,APPLY ,PRE-COMPILE-HOOKS>>

<DEFINE INSTALL-PRE-COMPILE-HOOK ("AUX" V)
    <COND (<GASSIGNED? PRE-COMPILE!-HOOKS!-ZILF>
           <SET V ,PRE-COMPILE!-HOOKS!-ZILF>
           <COND (<AND <N==? .V ,PRE-COMPILE-HOOK-F>
                       <NOT <MEMQ .V ,PRE-COMPILE-HOOKS>>>
                  <SETG PRE-COMPILE-HOOKS (.V !,PRE-COMPILE-HOOKS)>)>)>
    <SETG PRE-COMPILE!-HOOKS!-ZILF ,PRE-COMPILE-HOOK-F>>

<ENDPACKAGE>
