<VERSION ZIP>

<INSERT-FILE "testing">

<OBJECT STARTROOM
    (IN ROOMS)
    (DESC "Start Room")
    (LDESC "Ldesc.")
    (FLAGS LIGHTBIT)>

<OBJECT APPLE
    (IN STARTROOM)
    (DESC "apple")
    (SYNONYM APPLE)
    (FLAGS VOWELBIT TAKEBIT EDIBLEBIT)>

<OBJECT BANANA
    (IN STARTROOM)
    (DESC "banana")
    (SYNONYM BANANA)
    (FLAGS TAKEBIT EDIBLEBIT)>

<OBJECT HAT
    (IN STARTROOM)
    (DESC "hat")
    (SYNONYM HAT)
    (FLAGS TAKEBIT WEARBIT)>

<OBJECT CAGE
    (IN STARTROOM)
    (DESC "cage")
    (SYNONYM CAGE)
    (FLAGS CONTBIT TRANSBIT OPENABLEBIT TAKEBIT)>

<OBJECT BOX
    (IN STARTROOM)
    (DESC "box")
    (SYNONYM BOX)
    (FLAGS CONTBIT OPENABLEBIT TAKEBIT)>

<OBJECT DESK
    (IN STARTROOM)
    (DESC "desk")
    (SYNONYM DESK)
    (FLAGS SURFACEBIT)>

<OBJECT BUCKET
    (IN STARTROOM)
    (DESC "bucket")
    (SYNONYM BUCKET)
    (FLAGS CONTBIT OPENBIT TAKEBIT)>

<TEST-SETUP ()
    <MOVE ,WINNER ,STARTROOM>
    <MOVE ,APPLE ,STARTROOM>
    <MOVE ,BANANA ,STARTROOM>
    <MOVE ,HAT ,STARTROOM>
    <FCLEAR ,HAT ,WORNBIT>
    <MOVE ,CAGE ,STARTROOM>
    <FCLEAR ,CAGE ,OPENBIT>
    <MOVE ,BOX ,STARTROOM>
    <FCLEAR ,BOX ,OPENBIT>
    <MOVE ,DESK ,STARTROOM>
    <MOVE ,BUCKET ,STARTROOM>
    <FSET ,BUCKET ,OPENBIT>>

<TEST-CASE ("Open container, revealing contents")
    <MOVE ,APPLE ,BOX>
    <COMMAND [OPEN BOX]>
    <EXPECT "You open the box.|In the box is an apple.|">>

<TEST-CASE ("Take item from closed container")
    <MOVE ,APPLE ,CAGE>
    <COMMAND [TAKE APPLE]>
    <EXPECT "The cage is in the way.|">
    <COMMAND [TAKE CAGE]>
    <EXPECT "You pick up the cage.|">
    <COMMAND [TAKE APPLE]>
    <EXPECT "The cage is in the way.|">>

<TEST-GO ,STARTROOM>
