using System.Diagnostics.CodeAnalysis;

[assembly: UnconditionalSuppressMessage(
    "Trimming",
    "IL2075",
    Justification = "Generated by T4.BuildTools ToString helper in template base class.",
    Scope = "member",
    Target = "M:ZilfPub.IndexPageBase.ToStringInstanceHelper.ToStringWithCulture(System.Object)")]

[assembly: UnconditionalSuppressMessage(
    "Trimming",
    "IL2075",
    Justification = "Generated by T4.BuildTools ToString helper in template base class.",
    Scope = "member",
    Target = "M:ZilfPub.SourcePageBase.ToStringInstanceHelper.ToStringWithCulture(System.Object)")]

[assembly: UnconditionalSuppressMessage(
    "Trimming",
    "IL2075",
    Justification = "Generated by T4.BuildTools ToString helper in template base class.",
    Scope = "member",
    Target = "M:ZilfPub.PlayPageBase.ToStringInstanceHelper.ToStringWithCulture(System.Object)")]
