<?xml version="1.0" encoding="utf-8"?>
<!-- Copied from IronPython and modified. See Build/IronPython-License.txt. -->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MajorVersion>0</MajorVersion>
    <MinorVersion>11</MinorVersion>
    <MicroVersion>0</MicroVersion>
    <!-- Allowed: alpha,beta,candidate,final -->
    <ReleaseLevel>candidate</ReleaseLevel>
    <!-- If ReleaseLevel is "final", ReleaseSerial should be 0 -->
    <ReleaseSerial>1</ReleaseSerial>

    <AssemblyRevision>0</AssemblyRevision>
  </PropertyGroup>

  <PropertyGroup>
    <Product>ZILF</Product>
    <Company />
    <Version>$(MajorVersion).$(MinorVersion)</Version>
    <Authors>Tara McGrew</Authors>
    <Copyright>Copyright 2010-$([System.DateTime]::Now.ToString('yyyy')) Tara McGrew</Copyright>
  </PropertyGroup>
</Project>
