<PACKAGE "CLOSURE">

<ENTRY CLOSURE APPLY-CLOSURE>

<NEWTYPE CLOSURE VECTOR '!<VECTOR <LIST [REST !<LIST ATOM ANY>]> FUNCTION>>

<DEFINE APPLY-CLOSURE (C:CLOSURE "ARGS" ARGS)
    <EVAL `<BIND ~<1 .C> <APPLY ~<2 .C> ~!.ARGS>>>>

<APPLYTYPE CLOSURE ,APPLY-CLOSURE>

<DEFINE CLOSURE ("BIND" ENV FUNC:FUNCTION "TUPLE" ATOMS:<LIST [REST ATOM]> "AUX" BINDINGS)
    <SET BINDINGS <MAPF ,LIST
                        <FUNCTION (A) (.A <VALUE .A .ENV>)>
                        .ATOMS>>
    <CHTYPE [.BINDINGS .FUNC] CLOSURE>>

<ENDPACKAGE>
