<PACKAGE "QQ">

<ENTRY QUASIQUOTE TILDE>

<NEWTYPE TILDE LIST '!<<PRIMTYPE LIST> ANY>>

<DEFINE QUASIQUOTE ("BIND" ENV 'STRUC "AUX" (ALLOW-SPLICING? <>))
    <QQ-IMPL .ENV .STRUC>>

<DEFINE UNQUOTE? (OBJ)
    <TYPE? .OBJ TILDE>>

<DEFINE UNQUOTE-SPLICING? (OBJ)
    <DECL? .OBJ '<TILDE SEGMENT>>>

<DEFINE QQ-IMPL (ENV STRUC "AUX" (P <PRIMTYPE .STRUC>) (T <TYPE .STRUC>))
    <COND (<UNQUOTE-SPLICING? .STRUC>
           <OR .ALLOW-SPLICING? <ERROR UNQUOTE-SPLICING-NOT-ALLOWED-THERE .STRUC>>
           <MAPRET !<EVAL <CHTYPE <1 .STRUC> FORM> .ENV>>)
          (<UNQUOTE? .STRUC>
           <EVAL <1 .STRUC> .ENV>)
          (<OR <==? .T STRING>
               <NOT <STRUCTURED? .STRUC>>>
           .STRUC)
          (<NOT <AND <GBOUND? .P> <APPLICABLE? ,.P>>>
           <ERROR CANNOT-RECREATE-PRIMTYPE .P>)
          (ELSE
           <CHTYPE <APPLY ,.P !<QQ-ELEMS .ENV .STRUC>> .T>)>>

<DEFINE QQ-ELEMS (ENV STRUC "AUX" (ALLOW-SPLICING? T))
    <MAPF ,VECTOR
          <FUNCTION (I) <QQ-IMPL .ENV .I>>
          .STRUC>>

<DEFINE WRAP-QQ ("ARGS" A) <FORM QUASIQUOTE !.A>>
<DEFINE WRAP-UQ ("ARGS" A) <CHTYPE .A TILDE>>

;"TODO: USE READER-MACROS"
<COND (<GASSIGNED? MAKE-PREFIX-MACRO!-READER-MACROS>
       <MAKE-PREFIX-MACRO!-READER-MACROS !\` ,WRAP-QQ>
       <MAKE-PREFIX-MACRO!-READER-MACROS !\~ ,WRAP-UQ>)>

<ENDPACKAGE>
