<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Description>Provides an assembly language parser for ZAPF.</Description>
    <TargetFrameworkProfile />
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\Zilf.licenseheader">
      <Link>Zilf.licenseheader</Link>
    </None>
  </ItemGroup>
</Project>