<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Provides an assembly language parser for ZAPF.</Description>
    <TargetFrameworkProfile />
    <Nullable>enable</Nullable>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
  </PropertyGroup>
</Project>