<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RuntimeIdentifiers>win-x86;win-x64;linux-arm;linux-x64;osx-x64</RuntimeIdentifiers>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <OutputType>Exe</OutputType>
    <Description>The ZIL Implementation You Really, Really Like.</Description>
    <Deterministic>false</Deterministic>
    <Nullable>enable</Nullable>
	<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <!--<PropertyGroup Condition="!($(PortableTarget))">
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>-->
  <ItemGroup>
    <PackageReference Include="MSBuildTasks" Version="1.5.0.235" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ReadLine" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Zilf.Emit\Zilf.Emit.csproj" />
    <ProjectReference Include="..\Zilf.Common\Zilf.Common.csproj" />
  </ItemGroup>

  <!-- only use the analyzer if it's been built for this target -->
  <PropertyGroup>
    <ZilfAnalyzersAssembly>..\Analyzers\ZilfAnalyzers\ZilfAnalyzers\bin\$(Configuration)\$(TargetFramework)\ZilfAnalyzers.dll</ZilfAnalyzersAssembly>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>7</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>7</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Analyzer Condition="Exists('$(ZilfAnalyzersAssembly)')" Include="$(ZilfAnalyzersAssembly)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Analyzers\ZilfSourceGenerators\ZilfSourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
	
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>