<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2020.1.0" />
    <PackageReference Include="JunitXml.TestLogger" Version="2.1.78" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.7.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="16.7.3069">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.2" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)src\Analyzers\ZilfAnalyzers\ZilfAnalyzers.csproj" />
  </ItemGroup>

</Project>
