<?xml version="1.0" encoding="utf-8"?>

<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="16.0">
  <PropertyGroup>
    <TarOutputFile>$(PackageDir)\$(PackageName).tar.gz</TarOutputFile>
    <TarStageDir>$(PackageDir)\tar_temp_$(PackageName)</TarStageDir>
  </PropertyGroup>

  <Target Name="TarPackage"
          DependsOnTargets="Publish"
          AfterTargets="Package"
          Outputs="$(TarOutputFile)"
          Condition="$(UnixTarget) AND '$(OS)' == 'Unix'">
    <MakeDir Directories="$(PackageDir)" Condition="!Exists('$(PackageDir)')" />
    <MakeDir Directories="$(TarStageDir)" Condition="!Exists('$(TarStageDir)')" />

    <ItemGroup>
      <!-- Include all files from the publish directory, but exclude test artifacts, pdbs, and apphost -->
      <TarFiles Include="$(StageDir)\bin\**\*" Exclude="$(StageDir)\bin\**\*.Tests.*;$(StageDir)\bin\**\*.pdb;$(StageDir)\bin\**\apphost*" />
    </ItemGroup>

    <Copy SourceFiles="@(TarFiles)"
          DestinationFiles="@(TarFiles->'$(TarStageDir)\$(PackageName)\%(RecursiveDir)%(Filename)%(Extension)')">
      <Output TaskParameter="DestinationFiles" ItemName="CopiedTarFiles" />
    </Copy>

    <ItemGroup>
      <_TarExe Include="@(CopiedTarFiles)" Condition="'%(Extension)' == ''">
        <_LowerFilename>$([MSBuild]::ValueOrDefault('%(Filename)', '').ToLower())</_LowerFilename>
      </_TarExe>
      <_TarExeLowered Include="@(_TarExe->'%(RootDir)%(Directory)%(_LowerFilename)')" />
    </ItemGroup>

    <Move SourceFiles="@(_TarExe)"
          DestinationFiles="@(_TarExeLowered)" />

    <Exec WorkingDirectory="$(TarStageDir)"
          Command="tar cvfz $(TarOutputFile) $(PackageName)" />

    <RemoveDir Directories="$(TarStageDir)" />
  </Target>
</Project>
