<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Product>ZILF</Product>
    <Version>0.8</Version>
    <Authors>Tara McGrew</Authors>
    <Company />
    <Description>A ZAP disassembler.</Description>
    <Copyright>Copyright 2010-2018 Tara McGrew</Copyright>
    <NeutralLanguage></NeutralLanguage>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>7</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>7</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Zapf\Zapf.csproj" />
  </ItemGroup>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>