/* Examples of code that should be generated by SubrWrapperGenerator. */

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using Zilf.Interpreter.Values;
using Zilf.Language;

namespace Zilf.Interpreter
{
    static partial class Subr_Wrappers
    {
        // Subr: SPNAME
        // Subr: PNAME
        // arg0 ("atom"): ZilAtom
        public static ZilObject SPNAME(string name, Context ctx, ZilObject[] args)
        {
            int i = 0;

            var site = new FunctionCallSite(name);

            ZilAtom arg0;

            // arg0 ("atom"): ZilAtom
            if (i >= args.Length)
            {
                // required argument is missing
                throw ArgumentCountError.WrongCount(site, 1, 1);
            }
            else if (args[i] is ZilAtom arg0_cast_1)
            {
                // expected type (ATOM)
                arg0 = arg0_cast_1;
                i++;
            }
            else
            {
                // argument is wrong type
                throw new ArgumentTypeError(site, i, "ATOM");
            }

            // end of expected arguments
            if (i < args.Length)
            {
                // too many arguments
                throw ArgumentCountError.WrongCount(site, 1, 1);
            }

            return Subrs.SPNAME(ctx, arg0);
        }

        // Subr: PARSE
        // arg0 ("text"): string
        // arg1 ("radix"): [Decl("'10"), ZilOptional(Default = 10)] int
        // arg2 ("lookupObList"): [Either(typeof(ObList), typeof(ZilList)), ZilOptional(Default = null)] ZilObject = null
        public static ZilObject PARSE(string name, Context ctx, ZilObject[] args)
        {
            int i = 0;
            int? recentSkippedArg = null;
            int? lastUnderachievingArg = null;

            var site = new FunctionCallSite(name);

            string arg0;
            int arg1;
            ZilObject? arg2;

            // arg0 ("text"): string
            if (i >= args.Length)
            {
                // required argument is missing
                throw ArgumentCountError.WrongCount(site, 1, 3);
            }
            else if (args[i] is ZilString { Text: string arg0_cast_1 })
            {
                // expected type (STRING)
                arg0 = arg0_cast_1;
                recentSkippedArg = null;
                i++;
            }
            else
            {
                // argument is wrong type
                throw new ArgumentTypeError(site, i, "STRING");
            }

            // arg1 ("radix"): [Decl("'10"), ZilOptional(Default = 10)] int
            if (i >= args.Length)
            {
                // optional argument is missing, use default
                arg1 = 10;
                recentSkippedArg ??= i;
            }
            else if (args[i] is ZilFix { Value: int arg1_cast_1 } && Decl.Check(ctx, args[i], Program.Parse(ctx, "'10").Single()))
            {
                // expected type (FIX) and matches Decl constraint
                arg1 = arg1_cast_1;
                i++;
            }
            else
            {
                // assume optional parameter is missing, use default
                recentSkippedArg ??= i;
                lastUnderachievingArg = i;
                arg1 = 10;
            }

            // arg2 ("lookupObList"): [Either(typeof(ObList), typeof(ZilList)), ZilOptional(Default = null)] ZilObject = null
            if (i >= args.Length)
            {
                // optional argument is missing, use default
                arg2 = null;
                recentSkippedArg ??= i;
            }
            else if (args[i] is ObList arg2_cast_1)
            {
                // expected type (OBLIST)
                arg2 = arg2_cast_1;
                i++;
            }
            else if (args[i] is ZilList arg2_cast_2)
            {
                // expected type (LIST)
                arg2 = arg2_cast_2;
                i++;
            }
            else
            {
                // assume optional parameter is missing, use default
                arg2 = null;
                recentSkippedArg ??= i;
                lastUnderachievingArg = i;
            }

            // end of expected arguments
            if (i < args.Length)
            {
                // too many arguments OR optional arguments had the wrong type

                // for <PARSE "foo" BAR BAZ> we'll get here because arg1 and arg2 are both optional.
                // ideally we'd throw an error like "PARSE: arg 2: expected '10 or OBLIST or LIST but found ATOM",
                // where the "or" constraint is the union of constraints for all subsequent arguments up to the
                // next required argument.
                // ZILF 0.9 prints:
                //     [error MDL0128] <stdin>:1: PARSE: arg 2: expected '10 and FIX, LIST, or OBLIST

                if (i >= 3)
                {
                    throw ArgumentCountError.WrongCount(site, 1, 3);
                }

                switch (recentSkippedArg)
                {
                    case 1:
                        // we skipped arg1 and arg2, so this extra argument could be a type mismatch for either
                        throw new ArgumentTypeError(site, i, "'10, OBLIST, or LIST");
                    case 2:
                        // we skipped arg2, so this extra argument could be a type mismatch for it
                        throw new ArgumentTypeError(site, i, "OBLIST or LIST");
                    default:
                        // there's no skipped argument that this extra one could be a type mismatch for
                        throw ArgumentCountError.TooMany(site, i + 1, lastUnderachievingArg + 1);
                }
            }

            return Subrs.PARSE(ctx, arg0, arg1, arg2);
        }

        // Subr: REMOVE
        // arg0 ("atomOrNameAndObList"): [Either(typeof(ZilAtom), typeof(RemoveParams.PnameAndObList))] object
        public static ZilObject REMOVE(string name, Context ctx, ZilObject[] args)
        {
            int i = 0;

            var site = new FunctionCallSite(name);

            // arg0 ("atomOrNameAndObList"): [Either(typeof(ZilAtom), typeof(RemoveParams.PnameAndObList))] object
            object arg0;
            if (i >= args.Length)
            {
                // required argument is missing
                throw ArgumentCountError.WrongCount(site, 1, 2);
            }
            else if (args[i] is ZilAtom arg0_cast_1)
            {
                // expected type (ATOM)
                arg0 = arg0_cast_1;
                i++;
            }
            else if (Structure_Wrappers.Parse_PnameAndObList(site, args, i) is { Success: true, Value: var structure, NextIndex: var next })
            {
                // expected type (parsed structure)
                arg0 = structure;
                i = next;
            }
            else
            {
                // argument is wrong type
                throw new ArgumentTypeError(site, i, "ATOM or STRING");
            }

            // end of expected arguments
            if (i < args.Length)
            {
                // too many arguments OR structure
            }

            return Subrs.REMOVE(ctx, arg0);
        }
        
        // Subr: SETG
        // MDL-ZIL? -> GLOBAL (top level only)
        // arg0 ("atom"): ZilAtom
        // arg1 ("value"): ZilObject
        public static ZilObject SETG(string name, Context ctx, ZilObject[] args)
        {
            if ((ctx.CurrentFile.Flags & FileFlags.MdlZil) != 0 && ctx.AtTopLevel)
            {
                return Subr_Wrappers.GLOBAL(name, ctx, args);
            }

            int i = 0;

            var site = new FunctionCallSite(name);

            // arg0 ("atom"): ZilAtom
            ZilAtom arg0;
            if (i >= args.Length)
            {
                throw ArgumentCountError.WrongCount(site, 2, 2);
            }
            else if (args[i] is ZilAtom arg0_cast_1)
            {
                arg0 = arg0_cast_1;
                i++;
            }
            else
            {
                throw new ArgumentTypeError(site, i, "ATOM");
            }

            // arg1 ("value"): ZilObject
            ZilObject arg1;
            if (i >= args.Length)
            {
                throw ArgumentCountError.WrongCount(site, 2, 2);
            }
            else
            {
                arg1 = args[i];
                i++;
            }

            if (i < args.Length)
            {
                throw ArgumentCountError.WrongCount(site, 2, 2);
            }

            return Subrs.SETG(ctx, arg0, arg1);
        }

        public static ZilObject GLOBAL(string name, Context ctx, ZilObject[] args)
        {
            throw new NotImplementedException();
        }

        // FSubr: GDECL
        // arg0 ("pairs"): DeclParams.AtomsDeclSequence[]
        public static ZilObject GDECL(string name, Context ctx, ZilObject[] args)
        {
            int i = 0;

            var site = new FunctionCallSite(name);

            // arg0 ("pairs"): DeclParams.AtomsDeclSequence[]
            Zilf.Interpreter.Subrs.DeclParams.AtomsDeclSequence[] arg0;
            List<Zilf.Interpreter.Subrs.DeclParams.AtomsDeclSequence> arg0_list = new();
            while (i < args.Length)
            {
                var arg0_parse_result = Structure_Wrappers.Parse_AtomsDeclSequence(site, args, i);
                if (arg0_parse_result.Success)
                {
                    arg0_list.Add(arg0_parse_result.Value);
                    i = arg0_parse_result.NextIndex;
                }
                else
                {
                    break;
                }
            }
            arg0 = arg0_list.ToArray();

            if (i < args.Length)
            {
                throw ArgumentCountError.WrongCount(site, 0, null);
            }

            return Subrs.GDECL(ctx, arg0);
        }
    }

    readonly record struct ParseResult<TStructure>(bool Success, int NextIndex, TStructure? Value, ArgumentDecodingError? Exception)
    {
        public ParseResult(ArgumentDecodingError Exception) : this(false, -1, default, Exception) { }

        public ParseResult(int NextIndex, TStructure Value) : this(true, NextIndex, Value, null) { }

        public void Deconstruct(out bool success, out int nextIndex, out TStructure? value)
        {
            success = Success;
            nextIndex = NextIndex;
            value = Value;
        }

        public void Deconstruct(out bool success, ArgumentDecodingError? exception)
        {
            success = Success;
            exception = Exception;
        }
    }

    static partial class Structure_Wrappers
    {
        // Sequence: RemoveParams.PnameAndObList
        // elem0 ("Pname"): string
        // elem1 ("ObList"): ObList
        public static ParseResult<Zilf.Interpreter.Subrs.RemoveParams.PnameAndObList> Parse_PnameAndObList(CallSite parentSite, ZilObject[] args, int startIndex)
        {
            int i = startIndex;

            var site = new StructuredArgumentCallSite(parentSite, startIndex);

            // elem0 ("Pname"): string
            string elem0;
            if (i >= args.Length)
            {
                return new(ArgumentCountError.WrongCount(site, 2, 2));
            }
            else if (args[i] is ZilString { Text: string elem0_cast_1 })
            {
                elem0 = elem0_cast_1;
                i++;
            }
            else
            {
                return new(new ArgumentTypeError(site, i, "STRING"));
            }

            // elem1 ("ObList"): ObList
            if (args[i] is ObList elem1)
            {
                i++;
            }
            else
            {
                return new(new ArgumentTypeError(site, i, "OBLIST"));
            }

            return new(i, new Subrs.RemoveParams.PnameAndObList
            {
                Pname = elem0,
                ObList = elem1,
            });
        }

        // Sequence: DeclParams.AtomsDeclSequence
        // elem0 ("Atoms"): AtomList
        // elem1 ("Decl"): ZilObject
        public static ParseResult<Zilf.Interpreter.Subrs.DeclParams.AtomsDeclSequence> Parse_AtomsDeclSequence(CallSite parentSite, ZilObject[] args, int startIndex)
        {
            int i = startIndex;

            var site = new StructuredArgumentCallSite(parentSite, startIndex);

            // elem0 ("Atoms"): AtomList
            Zilf.Interpreter.Subrs.DeclParams.AtomList elem0;
            if (i >= args.Length)
            {
                return new(ArgumentCountError.WrongCount(site, 2, 2));
            }
            if (Structure_Wrappers.Parse_AtomList(site, args, i) is (true, int next, var structure))
            {
                elem0 = structure;
                i = next;
            }
            else
            {
                return new(new ArgumentTypeError(site, i, "LIST"));
            }

            // elem1 ("Decl"): ZilObject
            ZilObject elem1;
            if (i >= args.Length)
            {
                return new(ArgumentCountError.WrongCount(site, 2, 2));
            }
            else
            {
                elem1 = args[i];
                i++;
            }

            return new(i, new Subrs.DeclParams.AtomsDeclSequence
            {
                Atoms = elem0,
                Decl = elem1,
            });
        }

        // Structure (LIST): DeclParams.AtomList
        // elem0 ("Atoms"): ZilAtom[]
        public static ParseResult<Zilf.Interpreter.Subrs.DeclParams.AtomList> Parse_AtomList(CallSite parentSite, ZilObject[] args, int startIndex)
        {
            int i = startIndex;

            var site = new StructuredArgumentCallSite(parentSite, startIndex);

            // elem0 ("Atoms"): ZilAtom[]
            List<ZilAtom> elem0_list = new();
            while (i < args.Length)
            {
                if (args[i] is ZilAtom elem0_cast_1)
                {
                    elem0_list.Add(elem0_cast_1);
                    i++;
                }
                else
                {
                    break;
                }
            }
            ZilAtom[] elem0 = elem0_list.ToArray();

            return new(i, new Subrs.DeclParams.AtomList
            {
                Atoms = elem0,
            });
        }
    }
}
