<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Description>Provides Z-machine utility classes for ZILF and ZAPF.</Description>
    <TargetFrameworkProfile />
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\Zilf.licenseheader">
      <Link>Zilf.licenseheader</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.Analyzers.Compatibility" Version="0.2.12-alpha">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>