/* Copyright 2010-2024 Tara McGrew
 * 
 * This file is part of ZILF.
 * 
 * ZILF is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ZILF is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with ZILF.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Collections.Generic;
using System.Linq;

namespace ZilfSourceGenerators
{
    /// <summary>
    /// Generates distinct names for items, based on a number of properties.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Each item is added to the distinguisher with an ordered list of properties.
    /// The number of properties may be different for each item, but each item must
    /// have at least one property, and its full list of properties must be unique.
    /// </para>
    /// 
    /// <para>
    /// For instance, to generate unique names for helper methods corresponding to
    /// predefined methods, the properties might be the predefined method's name and
    /// its parameter types.
    /// </para>
    /// 
    /// <para>
    /// To generate the unique name for an item, the distinguisher goes left-to-right
    /// through the item's properties, including each property in the name if it
    /// differs from the property at that position of any other item which has the same
    /// properties up to that point. The first property is always included in the name;
    /// if an item's properties are a prefix of every other item's properties, its name
    /// will consist only of the first property.
    /// </para>
    /// 
    /// <para>
    /// When items have a different number of properties, an item with a property in
    /// a given position is considered to differ from an item without it; the missing
    /// property will not be included in the name of the item without it.
    /// </para>
    /// 
    /// <para>
    /// Adding an item to the distinguisher may change the name of any item already in
    /// the distinguisher. If any item can't be given a unique name, an exception is
    /// thrown.
    /// </para>
    /// 
    /// <para>
    /// Example:
    /// </para>
    /// <list type="bullet">
    /// <item>Start with an empty distinguisher.</item>
    /// <item>Add Item1 with properties A, B, C. Its unique name is "A".</item>
    /// <item>Add Item2 with properties A, B, D. This changes the name of Item1 to "A_C",
    /// and assigns Item2 the name "A_D", because the second properties are identical.</item>
    /// <item>Add Item3 with properties A, B. Item1 retains the name "A_C", Item2 retains
    /// the name "A_D", and Item3 is assigned the name "A".</item>
    /// <item>Add Item4 with properties B, A, C. All existing items retain their names, and
    /// Item4 is assigned the name "B", because its first property is enough to
    /// distinguish it from the other items.</item>
    /// <item>Add Item5 with properties A. Item5 is assigned the name "A". Since the second
    /// property is now needed to distinguish it from some of the existing items, this
    /// changes the name of Item1 to "A_B_C", Item2 to "A_B_D", and Item3 to "A_B".</item>
    /// </list>
    /// </remarks>
    public class Distinguisher<TProp, TItem>
        where TProp : IEquatable<TProp>
        where TItem : notnull
    {
        /* The implementation of this class is based on a trie. Each node in the trie
         * corresponds to a property, and the children of a node correspond to the
         * possible values of that property. The trie is built as items are added, and
         * the names are generated by traversing the trie. */
        private class Node
        {
            public Dictionary<TProp, KeyedNode> Children { get; } = [];
        }

        private sealed class KeyedNode(TProp key) : Node
        {
            public TProp Key { get; } = key;
            public TItem? Item { get; set; }

            public KeyedNode(TProp key, TItem item) : this(key)
            {
                Item = item;
            }
        }

        private readonly Node root = new();

        public void Add(IEnumerable<TProp> properties, TItem item)
        {
            var node = root;

            foreach (var prop in properties)
            {
                if (!node.Children.TryGetValue(prop, out var child))
                {
                    child = new KeyedNode(prop);
                    node.Children.Add(prop, child);
                }

                node = child;
            }

            if (node is KeyedNode kn)
            {
                if (kn.Item is null)
                {
                    kn.Item = item;
                }
                else
                {
                    throw new InvalidOperationException("Item already exists with these properties.");
                }
            }
            else
            {
                throw new InvalidOperationException("Item has no properties.");
            }
        }

        public IEnumerable<(string name, TItem item)> GetUniqueNames(string delimiter = "_")
        {
            var nameStack = new Stack<TProp>();

            foreach (var pair in root.Children)
            {
                // The keys of the root node are the first properties of the items,
                // which are always included in the name.

                nameStack.Push(pair.Key);

                foreach (var result in Inner(pair.Value))
                {
                    yield return result;
                }

                nameStack.Pop();
            }

            yield break;

            IEnumerable<(string name, TItem item)> Inner(KeyedNode node)
            {
                // The node's key has already been pushed onto the stack if we've determined
                // that it needs to be included in the name.

                if (node.Item is not null)
                {
                    yield return (string.Join(delimiter, nameStack.Reverse()), node.Item);
                }

                // Now we need to make that decision for the node's children.
                // If there are no children, we're done.

                if (node.Children.Count == 0)
                {
                    yield break;
                }

                // If there's only one child, that means the child's key is a common prefix
                // and isn't needed to distinguish any of the child's items; however, if this
                // node has an item, the child's key is still needed to distinguish the
                // child's items from this node's item.

                // If there are multiple children, we need to include each child's key
                // to distinguish it from its siblings.

                // Therefore, we only need to include each child's key in the name if
                // there's more than one child, or if this node has an item.

                bool includeKey = node.Item is not null || node.Children.Count > 1;

                foreach (var pair in node.Children)
                {
                    if (includeKey)
                    {
                        nameStack.Push(pair.Key);
                    }

                    foreach (var result in Inner(pair.Value))
                    {
                        yield return result;
                    }

                    if (includeKey)
                    {
                        nameStack.Pop();
                    }
                }
            }
        }
    }
}
