/* Copyright 2010-2026 Tara McGrew
 *
 * This file is part of ZILF.
 *
 * ZILF is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ZILF is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ZILF.  If not, see <http://www.gnu.org/licenses/>.
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.Linq;

namespace ZilfSourceGenerators;

partial class SubrParserGenerator
{
    /// <summary>
    /// Base class for custom parameter nodes that handle ZilStructuredParam and ZilSequenceParam structures
    /// </summary>
    public abstract class CustomParameterNode : ParameterNode
    {
        /// <summary>
        /// Gets or sets the type annotated with <c>ZilStructuredParamAttribute</c> or <c>ZilSequenceParamAttribute</c> which this node handles.
        /// </summary>
        public ITypeSymbol StructureType { get; set; } = null!;
        /// <summary>
        /// Gets or sets a value indicating whether this parameter represents an array of the <see cref="StructureType"/>, rather than a single value.
        /// </summary>
        public bool IsArray { get; set; }
        /// <summary>
        /// Gets or sets a value indicating whether this parameter is marked as nullable (i.e. with a <c>'?'</c> suffix in the declaration).
        /// </summary>
        public bool IsNullable { get; set; }

        protected string GetHybridStructureTypeName()
        {
            return SymbolTypeToZil(StructureType.ToDisplayString()) ?? StructureType.Name;
        }
    }

    /// <summary>
    /// Parameter node for handling ZilSequenceParam structures like AdditionalSortParam
    /// </summary>
    public sealed class CustomSequenceParameterNode : CustomParameterNode
    {
        /// <summary>
        /// Gets or sets a value indicating whether this sequence parameter is required (must parse at least one element).
        /// </summary>
        public bool IsRequired { get; set; }

        public override string GetExpectedTypeName()
        {
            if (StructureType != null)
            {
                var fields = StructureType.GetMembers().OfType<IFieldSymbol>()
                    .Where(f => f.DeclaredAccessibility == Accessibility.Public && !f.IsStatic)
                    .OrderBy(f => f.Locations.FirstOrDefault()?.SourceSpan.Start ?? 0)
                    .ToArray();

                if (fields.Length > 0)
                {
                    var builder = new ParameterTreeBuilder(/*[]*/);
                    var nodes = builder.BuildTree(fields);
                    return BuildExpectedTypeDisplayPreservingOrder(
                        nodes.SelectMany(node => node.GetErrorExpectedTypes()),
                        GetHybridStructureTypeName());
                }
            }

            return GetHybridStructureTypeName();
        }

        public override System.Collections.Generic.IEnumerable<string> GetErrorExpectedTypes()
        {
            if (StructureType != null)
            {
                var fields = StructureType.GetMembers().OfType<IFieldSymbol>()
                    .Where(f => f.DeclaredAccessibility == Accessibility.Public && !f.IsStatic)
                    .OrderBy(f => f.Locations.FirstOrDefault()?.SourceSpan.Start ?? 0)
                    .ToArray();

                if (fields.Length > 0)
                {
                    var builder = new ParameterTreeBuilder(/*[]*/);
                    var nodes = builder.BuildTree(fields);
                    foreach (var node in nodes)
                    {
                        foreach (var type in node.GetErrorExpectedTypes())
                            yield return type;
                    }
                    yield break;
                }
            }

            foreach (var type in base.GetErrorExpectedTypes())
                yield return type;
        }

        public override void GenerateParsingStep(IndentedStringBuilder sb, GenerationContext ctx)
        {
            // Emit parsing helper for custom structure parameter
            // Ensure helper methods for the structure are already generated by TreeBasedGenerator.GenerateHelperMethods
            var fnName = $"TryParse_{ParameterId}";
            var resultVar = GetResultVariableName();
            var fullTypeName = StructureType.ToDisplayString();

            var isArrayStr = IsArray ? "array of " : "";
            sb.AppendLine($"// {nameof(CustomSequenceParameterNode)}: Match {isArrayStr}{GetHybridStructureTypeName()}");
            sb.AppendLine($"bool {fnName}({ctx.RankerParameter})");
            sb.AppendLine("{");
            sb.Indent();

            var helperName = $"Generated_Parse{StructureType.Name}_Helper";
            if (IsArray)
            {
                // For arrays of structures, repeatedly call the generated helper until it fails
                if (IsNullable)
                {
                    // sb.AppendLine($"// CustomSequenceParameterNode: nullable array");
                    sb.AppendLine($"var list = new System.Collections.Generic.List<{fullTypeName}>();");
                    sb.AppendLine($"bool parsedAny_{ParameterId}_{ctx.Depth} = false;");
                    sb.AppendLine($"bool encounteredFailureBeforeAny_{ParameterId}_{ctx.Depth} = false;");
                    sb.AppendLine($"while ({ctx.ArgIndexVar} < {ctx.ArgsVar}.Length)");
                    sb.AppendLine("{");
                    sb.Indent();
                    sb.AppendLine($"int savedArgIndex_{ParameterId}_{ctx.Depth} = {ctx.ArgIndexVar};");
                    sb.AppendLine($"if (!{helperName}({ctx.ArgsVar}, ref {ctx.ArgIndexVar}, context, new StructuredArgumentCallSite(site, {ctx.ArgIndexVar}), out var item, ref {ctx.RankerVar}))");
                    sb.AppendLine("{");
                    sb.Indent();
                    sb.AppendLine($"{ctx.ArgIndexVar} = savedArgIndex_{ParameterId}_{ctx.Depth};");
                    sb.AppendLine($"if (!parsedAny_{ParameterId}_{ctx.Depth})");
                    sb.AppendLine("{");
                    sb.Indent();
                    sb.AppendLine($"encounteredFailureBeforeAny_{ParameterId}_{ctx.Depth} = true;");
                    sb.Unindent();
                    sb.AppendLine("}");
                    sb.AppendLine("break; // no more valid structures");
                    sb.Unindent();
                    sb.AppendLine("}");
                    sb.AppendLine($"if ({ctx.ArgIndexVar} == savedArgIndex_{ParameterId}_{ctx.Depth}) break; // no progress, avoid infinite loop");
                    sb.AppendLine("list.Add(item);");
                    sb.AppendLine($"parsedAny_{ParameterId}_{ctx.Depth} = true;");
                    sb.Unindent();
                    sb.AppendLine("}");
                    sb.AppendLine($"if (encounteredFailureBeforeAny_{ParameterId}_{ctx.Depth}) return false;");
                    sb.AppendLine($"{resultVar} = list.Count == 0 ? null : list.ToArray();");
                }
                else
                {
                    // Required array: must parse at least one element
                    // sb.AppendLine($"// CustomSequenceParameterNode: required array");
                    sb.AppendLine($"var list = new System.Collections.Generic.List<{fullTypeName}>();");
                    sb.AppendLine($"bool parsedAny_{ParameterId}_{ctx.Depth} = false;");
                    sb.AppendLine($"bool encounteredFailureBeforeAny_{ParameterId}_{ctx.Depth} = false;");
                    sb.AppendLine($"while ({ctx.ArgIndexVar} < {ctx.ArgsVar}.Length)");
                    sb.AppendLine("{");
                    sb.Indent();
                    sb.AppendLine($"int savedArgIndex_{ParameterId}_{ctx.Depth} = {ctx.ArgIndexVar};");
                    sb.AppendLine($"if (!{helperName}({ctx.ArgsVar}, ref {ctx.ArgIndexVar}, context, new StructuredArgumentCallSite(site, {ctx.ArgIndexVar}), out var item, ref {ctx.RankerVar}))");
                    sb.AppendLine("{");
                    sb.Indent();
                    sb.AppendLine($"{ctx.ArgIndexVar} = savedArgIndex_{ParameterId}_{ctx.Depth};");
                    sb.AppendLine($"if (!parsedAny_{ParameterId}_{ctx.Depth})");
                    sb.AppendLine("{");
                    sb.Indent();
                    sb.AppendLine($"encounteredFailureBeforeAny_{ParameterId}_{ctx.Depth} = true;");
                    sb.Unindent();
                    sb.AppendLine("}");
                    sb.AppendLine("break; // stop parsing elements on first failure");
                    sb.Unindent();
                    sb.AppendLine("}");
                    sb.AppendLine($"if ({ctx.ArgIndexVar} == savedArgIndex_{ParameterId}_{ctx.Depth}) break; // no progress, avoid infinite loop");
                    sb.AppendLine("list.Add(item);");
                    sb.AppendLine($"parsedAny_{ParameterId}_{ctx.Depth} = true;");
                    sb.Unindent();
                    sb.AppendLine("}");
                    sb.AppendLine($"if (encounteredFailureBeforeAny_{ParameterId}_{ctx.Depth}) return false;");
                    if (IsRequired)
                    {
                        sb.AppendLine($"if (list.Count == 0) {{ {ctx.RankerVar}.WrongCount(0, {ctx.SiteVar}, 1, null, false); return false; }}");
                    }
                    sb.AppendLine($"{resultVar} = list.ToArray();");
                }
            }
            else
            {
                // Single structure: delegate to generated helper which will throw on error
                var expectedTypeDisplay = BuildExpectedTypeDisplay(GetErrorExpectedTypes(), GetHybridStructureTypeName());
                // sb.AppendLine($"// CustomSequenceParameterNode: single structure");
                // Declare the typed temporary in the outer scope. We intentionally
                // declare `_singleParsed` here (rather than using an inline
                // `out var`) because the generator later emits a separate
                // assignment of the parsed value to the `result_{id}` variable
                // in a different scope. Declaring the temp in the outer scope
                // keeps the variable in-scope for that assignment and avoids
                // accidental CS0103 errors in the generated code.
                sb.AppendLine($"{fullTypeName} _singleParsed = default!;");
                var helperSiteExpr = ctx.CallerArgIndexVar != null
                    ? $"new StructuredArgumentCallSite({ctx.SiteVar}, {ctx.ArgIndexVar})"
                    : ctx.SiteVar;
                sb.AppendLine($"if (!{helperName}({ctx.ArgsVar}, ref {ctx.ArgIndexVar}, context, {helperSiteExpr}, out _singleParsed, ref {ctx.RankerVar}))");
                sb.AppendLine("{");
                sb.Indent();
                sb.AppendLine("return false;");
                sb.Unindent();
                sb.AppendLine("}");
                sb.AppendLine();
                sb.AppendLine($"{resultVar} = _singleParsed;");
            }

            sb.AppendLine("return true;");
            sb.Unindent();
            sb.AppendLine("}");
        }

        public override void GenerateInvokeStep(IndentedStringBuilder sb, GenerationContext ctx)
        {
            var fnName = $"TryParse_{ParameterId}";
            if (IsOptional)
            {
                sb.AppendLine($"if (!{fnName}({ctx.RankerArgument}))");
                sb.AppendLine("{");
                sb.Indent();
                sb.AppendLine($"// Optional sequence-structure parameter not matched, using default value");
                sb.AppendLine($"{GetResultVariableName()} = {GetDefaultValueExpression()};");
                sb.Unindent();
                sb.AppendLine("}");
            }
            else
            {
                var expectedTypeDisplay = BuildExpectedTypeDisplay(GetErrorExpectedTypes(), GetHybridStructureTypeName());
                var expectedTypeEscaped = expectedTypeDisplay.Replace("\"", "\\\"");
                if (!string.IsNullOrEmpty(ctx.CallerArgIndexVar))
                {
                    sb.AppendLine($"if (!{fnName}({ctx.RankerArgument}))");
                    sb.AppendLine("{");
                    sb.Indent();
                    sb.AppendLine($"{ctx.CallerArgIndexVar} = {ctx.ArgIndexVar};");
                    sb.AppendLine("return false;");
                    sb.Unindent();
                    sb.AppendLine("}");
                }
                else
                {
                    sb.AppendLine($"if (!{fnName}({ctx.RankerArgument}))");
                    sb.AppendLine("{");
                    sb.Indent();
                    sb.AppendLine($"{ctx.RankerVar}.ThrowIfError();");
                    sb.AppendLine($"throw new ArgumentTypeError({ctx.SiteVar}, {ctx.ArgIndexVar}, \"{expectedTypeEscaped}\");");
                    sb.Unindent();
                    sb.AppendLine("}");
                }
            }
        }
    }

    /// <summary>
    /// Parameter node for handling ZilStructuredParam structures like CondClause
    /// This node mirrors the behavior of CustomSequenceParameterNode but for
    /// "structured" parameters (attribute: ZilStructuredParam).
    /// Implemented as a lightweight node that emits a parsing-step which
    /// delegates to generated helper methods (Generated_Parse{Type}_Helper).
    /// </summary>
    public sealed class CustomStructuredParameterNode : CustomParameterNode
    {
        /// <summary>
        /// Gets or sets a value indicating whether this parameter is marked as required.
        /// </summary>
        /// <remarks>
        /// Only applies when <see cref="CustomParameterNode.IsArray"/> is true. If true, at least one element must be parsed;
        /// otherwise, the parameter can be an empty array.
        /// </remarks>
        public bool IsRequired { get; set; }

        public override System.Collections.Generic.IEnumerable<string> GetErrorExpectedTypes()
        {
            if (StructureType != null)
            {
                var structuredAttr = StructureType.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.Name == "ZilStructuredParamAttribute" ||
                    a.AttributeClass?.Name == "ZilStructuredParam");
                if (structuredAttr != null && structuredAttr.ConstructorArguments.Length > 0)
                {
                    var expectedTypeConstant = structuredAttr.ConstructorArguments[0];
                    if (!expectedTypeConstant.IsNull)
                    {
                        var expectedTypeCSharp = expectedTypeConstant.ToCSharpString();
                        if (!string.IsNullOrEmpty(expectedTypeCSharp))
                        {
                            var lastDot = expectedTypeCSharp.LastIndexOf('.');
                            var atomName = lastDot >= 0 ? expectedTypeCSharp.Substring(lastDot + 1) : expectedTypeCSharp;
                            yield return IsArray ? atomName + " array" : atomName;
                            yield break;
                        }
                    }
                }
            }

            foreach (var type in base.GetErrorExpectedTypes())
                yield return type;
        }

        public override void GenerateParsingStep(IndentedStringBuilder sb, GenerationContext ctx)
        {
            var fnName = $"TryParse_{ParameterId}";
            var resultVar = GetResultVariableName();
            var fullTypeName = StructureType.ToDisplayString();

            var isArrayStr = IsArray ? "array of " : "";
            sb.AppendLine($"// {nameof(CustomStructuredParameterNode)}: Match {isArrayStr}{GetHybridStructureTypeName()}");
            sb.AppendLine($"bool {fnName}({ctx.RankerParameter})");
            sb.AppendLine("{");
            sb.Indent();

            var helperName = $"Generated_Parse{StructureType.Name}_Helper";

            if (IsArray)
            {
                // Array of structured params: repeatedly call helper until it fails
                sb.AppendLine($"var list = new System.Collections.Generic.List<{fullTypeName}>();");
                sb.AppendLine($"while ({ctx.ArgIndexVar} < {ctx.ArgsVar}.Length)");
                sb.AppendLine("{");
                sb.Indent();
                sb.AppendLine($"int savedArgIndex_{ParameterId}_{ctx.Depth} = {ctx.ArgIndexVar};");
                sb.AppendLine($"if (!{helperName}({ctx.ArgsVar}, ref {ctx.ArgIndexVar}, context, new StructuredArgumentCallSite(site, {ctx.ArgIndexVar}), out var item, ref {ctx.RankerVar}))");
                sb.AppendLine("{");
                sb.Indent();
                sb.AppendLine($"{ctx.ArgIndexVar} = savedArgIndex_{ParameterId}_{ctx.Depth};");
                sb.AppendLine("break;");
                sb.Unindent();
                sb.AppendLine("}");
                sb.AppendLine($"if ({ctx.ArgIndexVar} == savedArgIndex_{ParameterId}_{ctx.Depth}) break; // no progress, avoid infinite loop");
                sb.AppendLine("list.Add(item);");
                sb.Unindent();
                sb.AppendLine("}");
                if (IsRequired)
                {
                    sb.AppendLine($"if (list.Count == 0) {{ {ctx.RankerVar}.WrongCount(0, {ctx.SiteVar}, 1, null, false); return false; }}");
                    sb.AppendLine($"{resultVar} = list.ToArray();");
                }
                else if (IsNullable)
                {
                    sb.AppendLine($"{resultVar} = list.Count == 0 ? null : list.ToArray();");
                }
                else
                {
                    sb.AppendLine($"{resultVar} = list.ToArray();");
                }
            }
            else
            {
                // Single structured param: delegate to helper
                var expectedTypeDisplay = BuildExpectedTypeDisplay(GetErrorExpectedTypes(), GetHybridStructureTypeName());
                sb.AppendLine($"{fullTypeName} _singleParsed = default!;");
                var helperSiteExpr = ctx.CallerArgIndexVar != null
                    ? $"new StructuredArgumentCallSite({ctx.SiteVar}, {ctx.ArgIndexVar})"
                    : ctx.SiteVar;
                sb.AppendLine($"if (!{helperName}({ctx.ArgsVar}, ref {ctx.ArgIndexVar}, context, {helperSiteExpr}, out _singleParsed, ref {ctx.RankerVar}))");
                sb.AppendLine("{");
                sb.Indent();
                sb.AppendLine("return false;");
                sb.Unindent();
                sb.AppendLine("}");
                sb.AppendLine($"{resultVar} = _singleParsed;");
            }

            sb.AppendLine("return true;");
            sb.Unindent();
            sb.AppendLine("}");
        }

        public override void GenerateInvokeStep(IndentedStringBuilder sb, GenerationContext ctx)
        {
            var fnName = $"TryParse_{ParameterId}";
            var resultVar = GetResultVariableName();
            if (IsOptional)
            {
                sb.AppendLine($"if (!{fnName}({ctx.RankerArgument}))");
                sb.AppendLine("{");
                sb.Indent();

                // Check if we have arguments available but parsing failed
                sb.AppendLine($"if ({ctx.ArgIndexVar} < {ctx.ArgsVar}.Length)");
                sb.AppendLine("{");
                sb.Indent();

                // If no detailed error was recorded, try to probe for better error info
                // TODO: This "probing" sure looks redundant, but it seems necessary for correct error messages. Figure out why.
                sb.AppendLine($"if (!{ctx.RankerVar}.HasError && {ctx.ArgsVar}[{ctx.ArgIndexVar}] is IStructure)");
                sb.AppendLine("{");
                sb.Indent();
                sb.AppendLine($"var probeIndex = {ctx.ArgIndexVar};");
                sb.AppendLine("var probeRanker = new ErrorRanker();");
                sb.AppendLine($"Generated_Parse{StructureType.Name}_Helper({ctx.ArgsVar}, ref probeIndex, context, {ctx.SiteVar}, out var _, ref probeRanker);");
                sb.AppendLine("if (probeRanker.HasError)");
                sb.AppendLine("{");
                sb.Indent();
                sb.AppendLine($"{ctx.RankerVar} = probeRanker;");
                sb.Unindent();
                sb.AppendLine("}");
                sb.Unindent();
                sb.AppendLine("}");

                // Let the ranker throw any detailed structured parsing errors it may have recorded
                sb.AppendLine($"{ctx.RankerVar}.ThrowIfError();");

                sb.Unindent();
                sb.AppendLine("}");

                // No arguments available or no detailed error - use default
                sb.AppendLine($"{resultVar} = {GetDefaultValueExpression()};");
                sb.Unindent();
                sb.AppendLine("}");
            }
            else
            {
                var expectedTypeDisplay = BuildExpectedTypeDisplay(GetErrorExpectedTypes(), GetHybridStructureTypeName());
                var expectedTypeEscaped = expectedTypeDisplay.Replace("\"", "\\\"");
                if (!string.IsNullOrEmpty(ctx.CallerArgIndexVar))
                {
                    sb.AppendLine($"if (!{fnName}({ctx.RankerArgument}))");
                    sb.AppendLine("{");
                    sb.Indent();
                    sb.AppendLine($"{ctx.CallerArgIndexVar} = {ctx.ArgIndexVar};");
                    sb.AppendLine("return false;");
                    sb.Unindent();
                    sb.AppendLine("}");
                }
                else
                {
                    sb.AppendLine($"if (!{fnName}({ctx.RankerArgument}))");
                    sb.AppendLine("{");
                    sb.Indent();

                    // Build combined expected type list from prior optional parameters
                    if (ctx.PriorOptionalNodes.Length > 0)
                    {
                        sb.AppendLine("var expectedTypes = new System.Collections.Generic.List<string>();");
                        sb.AppendLine("var hasPriorOptionalMismatch = false;");
                        // Include prior optional types only if they had a mismatch (failed to parse available argument)
                        foreach (var priorOpt in ctx.PriorOptionalNodes)
                        {
                            var priorExpectedDisplay = BuildExpectedTypeDisplay(priorOpt.GetErrorExpectedTypes(), priorOpt.GetExpectedTypeName());
                            var priorExpectedEscaped = priorExpectedDisplay.Replace("\"", "\\\"");
                            sb.AppendLine($"if (optionalMismatch_{priorOpt.ParameterId})");
                            sb.AppendLine("{");
                            sb.Indent();
                            sb.AppendLine("hasPriorOptionalMismatch = true;");
                            sb.AppendLine($"expectedTypes.Add(\"{priorExpectedEscaped}\");");
                            sb.Unindent();
                            sb.AppendLine("}");
                        }
                        sb.AppendLine($"expectedTypes.Add(\"{expectedTypeEscaped}\");");
                        sb.AppendLine("var combinedExpected = expectedTypes.Count == 1 ? expectedTypes[0] : expectedTypes.Count == 2 ? expectedTypes[0] + \" or \" + expectedTypes[1] : string.Join(\", \", expectedTypes.GetRange(0, expectedTypes.Count - 1)) + \", or \" + expectedTypes[expectedTypes.Count - 1];");

                        // Try to get detailed error by probing the structure if it's a structure argument
                        // TODO: This "probing" sure looks redundant, but it seems necessary for correct error messages. Figure out why.
                        sb.AppendLine($"if ({ctx.ArgIndexVar} < {ctx.ArgsVar}.Length && {ctx.ArgsVar}[{ctx.ArgIndexVar}] is IStructure)");
                        sb.AppendLine("{");
                        sb.Indent();
                        sb.AppendLine($"var probeIndex = {ctx.ArgIndexVar};");
                        sb.AppendLine("var probeRanker = new ErrorRanker();");
                        sb.AppendLine($"if (!Generated_Parse{StructureType.Name}_Helper({ctx.ArgsVar}, ref probeIndex, context, {ctx.SiteVar}, out var _, ref probeRanker) && probeRanker.HasError)");
                        sb.AppendLine("{");
                        sb.Indent();
                        sb.AppendLine($"if (!hasPriorOptionalMismatch || !probeRanker.IsWrongType || probeRanker.CurrentConstraint != \"{expectedTypeEscaped}\" || probeRanker.CurrentIndex != {ctx.ArgIndexVar})");
                        sb.AppendLine("{");
                        sb.Indent();
                        sb.AppendLine("probeRanker.Throw();");
                        sb.Unindent();
                        sb.AppendLine("}");
                        sb.Unindent();
                        sb.AppendLine("}");
                        sb.Unindent();
                        sb.AppendLine("}");

                        sb.AppendLine($"{ctx.RankerVar}.WrongType({ctx.ArgIndexVar}, {ctx.SiteVar}, {ctx.ArgIndexVar}, combinedExpected);");
                        sb.AppendLine($"throw new ArgumentTypeError({ctx.SiteVar}, {ctx.ArgIndexVar}, combinedExpected);");
                    }
                    else
                    {
                        // Let the ranker throw any detailed errors it has, or fall back to generic error
                        sb.AppendLine($"{ctx.RankerVar}.ThrowIfError();");
                        sb.AppendLine($"{ctx.RankerVar}.WrongType({ctx.ArgIndexVar}, {ctx.SiteVar}, {ctx.ArgIndexVar}, \"{expectedTypeEscaped}\");");
                        sb.AppendLine($"throw new ArgumentTypeError({ctx.SiteVar}, {ctx.ArgIndexVar}, \"{expectedTypeEscaped}\");");
                    }

                    sb.Unindent();
                    sb.AppendLine("}");
                }
            }
        }
    }
}
